---
- hosts: all
  become: yes
  vars_files:
    - vars/main.yml
    - vars/secrets.yml
  tasks:
    - name: Update the system-wide packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install the pip python package manager
      apt:
        name: python3-pip

    - include_tasks: create_users_and_groups.yml
    - include_tasks: setup_django_app.yml
    - include_tasks: setup_supervisor.yml
    - include_tasks: setup_nginx.yml
