---
- hosts: all
  become: yes
  vars:
    - app_dir: /apps/bookstorewindow
    - venv_dir: /apps/bookstorewindow/venv
  vars_files:
    - vars/secrets.yml
  tasks:
    - name: Update the system-wide packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install the pip python package manager
      apt:
        name: python3-pip

    - name: Install the python packages required by the app in a virtualenv
      pip:
        requirements: "{{ app_dir }}/requirements/base.txt"
        virtualenv: "{{ venv_dir }}"

    - name: Insert the Google API key to the python virtualenv activate script
      lineinfile:
        path: "{{ app_dir }}/venv/bin/activate"
        regexp: '^export GOOGLE_API_KEY='
        line: 'export GOOGLE_API_KEY={{ google_api_key }}'
