---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/secrets.yml
  tasks:
    - name: Provision a DigitalOcean droplet
      digital_ocean:
        api_token: "{{ digitalocean_access_token }}"
        state: present
        command: droplet
        name: staging.bookstorewindow
        size_id: s-1vcpu-1gb
        image_id: ubuntu-18-04-x64
        region_id: nyc1
        ssh_key_ids: "{{ digitalocean_ssh_key_id }}"
        unique_name: yes
      register: created_droplet

    - name: Add DigitalOcean hosts to inventory groups.
      add_host:
        name: "{{ created_droplet.droplet.ip_address }}"
        groups: "{{ created_droplet.droplet.name }}"

- hosts: staging.bookstorewindow
  remote_user: root
  gather_facts: false

  tasks:
    - name: Wait for port 22 to become available.
      local_action: "wait_for port=22 host={{ inventory_hostname }}"
