---

- name: Create the Gunicorn script file
  template:
    src: gunicorn_start.j2
    dest: "{{ venv_dir }}/bin/gunicorn_start"
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group }}"
    mode: 0755

- name: Create the application log folder
  file:
    path: "{{ app_log_dir }}"
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group }}"
    mode: 0774
    state: directory

- name: Create the application log file
  file:
    path: "{{ app_log_file }}"
    state: touch
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group }}"
    mode: 0664
