# Generated by Django 2.1.5 on 2019-01-28 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True)),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('google_book_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('volume_info', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='window.Book')),
            ],
            options={
                'ordering': ['google_book_id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'authors')},
        ),
    ]
