# Generated by Django 2.1.5 on 2019-01-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('window', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
