# Generated by Django 2.1.5 on 2019-01-28 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('window', '0002_book_publisher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volume',
            options={'ordering': ['google_book_id']},
        ),
    ]
