# Generated by Django 2.1.5 on 2019-01-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('window', '0003_auto_20190128_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
